[project]
name = "openflr-benchmarking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "flfm",
    "jax[cuda12]>=0.11.1",
    "torch",
    "torchvision",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
flfm = { git = "https://github.com/OpenFLR/flfm.git" }
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
